# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Pathways to global hydrogen production within planetary boundaries
author: M. Lejeune et al. 2025
logo: results/1_00_total_human_impact/SI_Fig5_force_interactions.png
copyright                   : "2025"  # Copyright year to be placed in the footer
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: False
only_build_toc_files: True

# # Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# # Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Michael-ljn/pathways-H2-prod-within-PBs  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: True
  use_repository_button: True
  use_multitoc_numbering: false
  collapse_navigation: true

